# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=30, verbose_name='Модель')),
                ('gear_box', models.CharField(choices=[('mech', 'Механическая'), ('auto', 'Автоматическая')], max_length=20, verbose_name='Коробка передач')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото')),
            ],
            options={
                'verbose_name_plural': 'Автомобили',
                'verbose_name': 'Автомобиль',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_ways.Car', verbose_name='Авто')),
            ],
            options={
                'verbose_name_plural': 'Сотрудники',
                'verbose_name': 'Сотрудник',
            },
        ),
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=80, verbose_name='Район')),
                ('schema', models.ImageField(upload_to='', verbose_name='Схема')),
            ],
            options={
                'verbose_name_plural': 'Маршруты',
                'verbose_name': 'Маршрут',
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='waybills',
            field=models.ManyToManyField(to='car_ways.Waybill', verbose_name='Маршруты'),
        ),
    ]
