# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_ways', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Car', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employe', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='waybill',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AddField(
            model_name='employe',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photos'),
        ),
        migrations.AddField(
            model_name='employe',
            name='with_licence',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employe',
            name='with_limitations',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='gear_box',
            field=models.CharField(choices=[('mech', 'Machanical'), ('auto', 'Automotive')], max_length=20, verbose_name='PPC'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mark',
            field=models.CharField(max_length=20, verbose_name='Mark'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=30, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photos'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_ways.Car', verbose_name='car'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='waybills',
            field=models.ManyToManyField(to='car_ways.Waybill', verbose_name='routes'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='area',
            field=models.CharField(max_length=80, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='schema',
            field=models.ImageField(upload_to='', verbose_name='Schema'),
        ),
    ]
