# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-29 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_ways', '0004_district_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='waybill',
            options={'verbose_name': 'Waybill', 'verbose_name_plural': 'Waybills'},
        ),
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_ways.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car_ways.District', verbose_name='District'),
        ),
    ]
